[package]
name = "nanai-shiftjis-notepad"
version.workspace = true
edition.workspace = true
license.workspace = true

[workspace]
members = ["nanai-shiftjis-notepad-dll"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR MIT AND Apache-2.0"

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
panic = "abort"
strip = "symbols"

[features]
win-reactor-ui = ["dep:windows-reactor"]
winio-ui = ["dep:winio"]
gpui-ui = ["dep:gpui"]
default = ["win-reactor-ui"]

[dependencies]
#UI
#cross
gpui = { version = "0.2.2", optional = true }
#winio
winio = { version = "0.11.0", optional = true }

#basic process
#cross
anyhow = "1.0.103"
encoding_rs = { version = "0.8.35" }
compio = { version = "0.19.1", features = ["fs", "runtime", "process"] }

[target.'cfg(target_os = "windows")'.dependencies]
#UI
#windows-reactor
windows-reactor = { git = "https://github.com/microsoft/windows-rs", branch = "master", optional = true }

#basic process
windows = { version = "0.62.2", features = ["ApplicationModel"] }

[target.'cfg(target_os = "windows")'.build-dependencies]
#UI
#windows
windows-reactor-setup = { git = "https://github.com/microsoft/windows-rs", branch = "master" }
