[package]
name = "nanai-shiftjis-reader-dll"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
windows = { version = "0.62", features = [
    "Foundation",
    "ApplicationModel",
    "Win32",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }
windows-core = { version = "0.62", default-features = false }
thiserror = "2"
